### PR TITLE
Metadata Launch Script

### LINKED ISSUE #11: Save acquisition JSON file from tile metadata
Save and convert/output the tile metadata dictionary to the aind-data-schema acquisition JSON spec.

- [ ] create a new launch repo outside of exaspim-control
- [ ] save the executed tile dictionary into the acquisition YAML file
- [ ] parse this tile dictionary from the YAML file into the aind-data-schema acquisition JSION spec

### PR DESCRIPTION
**Pull request by micahwoodard**
fixes #11 
- separate launch script
- creates and saves acquisition json in correct places at end of scan based on tile information in acquisition config

### CODE REVIEW

**Comment by micahwoodard** [comment]
@adamkglaser there are a couple of question I have about if some assumptions I've made are safe or not. I have them as comment in the metadata_launch.py. Let me know if this resembles what you were thinking for #11 issue.

**Comment by adamkglaser** [comment]
@micahwoodard these are all safe assumptions. It is safe to assume in general that there is one camera and one laser per tile. Even if we started doing something interleaved or with multiple cameras, I think we would always split them off into different files, which means they would be different "tiles" in the schema sense. The only funky one is the wavelength, and how to parse that. For now what you did is OK and for our own internal purposes we have to remember that we name the laser devices ABC nm. The only other option would be to consider adding an explicit wavelength property to the laser base class?

**Comment by micahwoodard** [comment]
Yeah I also thought another good way for wavelength would be to enforce in laser base class. I think that's a better than trying to parse the name which could become annoying, especially if others in the building are going to use this? I don't know I'll leave it up to you since it would require a refactor in voxel before being able to get merged

**Comment by adamkglaser** [comment]
@micahwoodard agreed it would be best to the laser class / voxel as well in parallel to this PR

**Comment by micahwoodard** [comment]
@adamkglaser I updated the launch script and then started a small unit test folder to try and confirm it would write correctly if the metadata was configured correctly. I'm not quite done with the unit tests, but we can merge and I can finish them up later

**Comment by micahwoodard** [comment]
@adamkglaser added metadata folder that contains class that inherits from voxel and contains aind specific variables

**Comment by adamkglaser** [comment]
@micahwoodard  I am OK to merge this now.

**Pull request merged**
