### PR TITLE
Fix update acquisition layer

### PR DESCRIPTION
**Pull request by micahwoodard**
- fix for acquisition_layer_update correctly

### CODE REVIEW

**Comment by micahwoodard** [comment]
need to test on instrument but pretty sure this is the fix

**Comment by micahwoodard** [comment]
also fixing yaml handler to handle np.int64 for step size value in config

**Comment by micahwoodard** [comment]
@adamkglaser tested on rig and working okay to merge in with approval

**Comment by adamkglaser** [comment]
@micahwoodard  ok great. Thanks, I will merge.

**Pull request merged**
